### ISSUE TITLE
Getting Build Error

### ISSUE THREAD

**Issue by jsolack** [pamu/PlaySystemMonitor#1]
Hello, i'm getting the follow error when i build this project

```
[error] Not a valid command: build (similar: idea)
[error] Not a valid project ID: build
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: build (similar: loaded-build, loadedBuild)
[error] build
[error]      ^
```

I have tried getting the project from github and from the activator ui and i get the same error

Thank you,

Jason

EDIT: I'm sorry this was my error!

**Comment by pamu** [comment]
@jsolack thanks :+1:
